### ISSUE TITLE
Request: LED path for Motorola Moto-G (2013)

### ISSUE THREAD

**Issue by Gummikavalier** [sam-hobbs/harbour-hammerhead-torch#5]
Thanks for the nice torch application. :)

For possible future releases I tested following path in Moto-G 2013 (Falcon) conversion from Piggz and it works.

Name in /etc/hw-release
`Motorola Moto-G (2013)`

LED path:
`/sys/class/leds/torch-light/brightness`

**Comment by sam-hobbs** [comment]
Hi,

Thanks for this. I have quite a busy week coming up but I will do my best to package a new version supporting the Moto G at the weekend.

Sam

**Comment by Gummikavalier** [comment]
Thanks! No hurry... I got it working by setting the path manually in the conf file, so it is just a matter of convenience. :)
